import { matchKeyword } from './keywords.js';
export const priorityOrder = ['Critical', 'High Impact', 'Medium Impact', 'Low Impact'];
export function analyzeRules(page, keywords, topics) {
  const issues = [];
  function add(id, priority, element, issue, evidence, why, fix, example = '') { issues.push({ id, priority, element, issue, evidence, why, fix, example, sourceUrl: page.url, basis: 'Observed evidence + rule-based recommendation' }); }
  const primary = keywords[0]; const topic = primary.keyword;
  if (page.robots.some(r => /\bnoindex\b|\bnone\b/i.test(r))) add('indexing', 'Critical', 'Robots directives', 'Confirm whether this page should be indexable', page.robots.join('; '), 'A noindex directive asks compliant search engines to exclude the page.', 'If this is intended as an organic landing page, remove noindex from the page or response headers after confirming the publishing intent.');
  if (!page.title) add('title-missing', 'High Impact', 'Title', 'Add a descriptive title tag', 'No title text extracted.', 'A title identifies the page in browser tabs and can inform search-result presentation.', `Write a concise title describing ${topic}, using only services and areas the business actually offers.`, topic);
  else if (primary.title.coverage < .7) add('title-topic', 'High Impact', 'Title', 'Make the title’s primary topic clearer', page.title, 'The title contains few terms from the primary query. Natural variations are welcome.', 'Lead with the actual page subject. Preserve brand positioning and avoid listing all keyword variations.', topic);
  if (page.title && (page.title.length < 20 || page.title.length > 70)) add('title-length', 'Low Impact', 'Title', 'Review the title’s search-result presentation', `${page.title.length} characters: ${page.title}`, 'Very short or long titles can be vague or truncated; pixel width and query context matter more than a rigid limit.', 'Keep the useful topic and differentiator; remove repetitive wording. Character length is a review cue, not a ranking rule.');
  if (!page.description) add('description-missing', 'Medium Impact', 'Meta description', 'Write a useful meta description', 'No meta description extracted.', 'A description can communicate relevance and encourage a click, although search engines may replace it.', 'Summarize the real offering and benefit, then include a relevant next step. Do not invent claims.');
  else if (page.description.length < 70 || page.description.length > 180) add('description-length', 'Low Impact', 'Meta description', 'Review the meta description', `${page.description.length} characters: ${page.description}`, 'This length can leave useful context out or lead to truncation.', 'Use natural copy centered on what the page actually provides; do not mechanically target a fixed character count.');
  if (!page.h1.length) add('h1-missing', 'High Impact', 'H1', 'Add a clear primary heading', 'No H1 extracted.', 'A clear heading helps visitors identify the purpose of the page.', 'Add one descriptive H1 that matches the actual offering and intent.', topic);
  else if (page.h1.length > 1) add('h1-multiple', 'Medium Impact', 'H1', 'Review multiple primary headings', page.h1.join(' | '), 'Multiple H1s are not inherently a ranking penalty, but can create an unclear content hierarchy.', 'Choose a primary page heading and use subordinate heading levels where appropriate.');
  else if (primary.h1.coverage < .7) add('h1-topic', 'High Impact', 'H1', 'Clarify the main heading’s topic', page.h1[0], 'The visible heading provides limited lexical alignment with the requested topic.', 'Describe the service or answer in natural language; confirm that the query matches the page’s real purpose.', topic);
  if (primary.intro.coverage < .5) add('intro', 'High Impact', 'Introduction', 'Establish the subject earlier', page.intro || 'No opening text extracted.', 'The first 120 extracted words do not clearly cover the main query terms.', 'Introduce the actual subject, intended audience, and useful next step near the beginning. Confirm the visible layout before editing.');
  if (page.wordCount < 150) add('thin', 'High Impact', 'Body content', 'Check the limited extractable content', `${page.wordCount} approximate words in static HTML.`, 'The retrieved page offers little text to evaluate. This may reflect client-rendered content rather than a thin visible page.', 'Check the rendered page and server-rendering first. Add useful scope, answers, or examples only where visitors need them; do not add filler.');
  if (page.hierarchyIssues.length) add('hierarchy', 'Medium Impact', 'Headings', 'Repair skipped heading levels', page.hierarchyIssues.join('; '), 'A logical outline improves navigation and accessibility.', 'Nest sections consistently, for example H1 → H2 → H3, without changing heading levels just for visual size.');
  if (!page.h2.length && page.wordCount >= 150) add('sections', 'Medium Impact', 'H2 headings', 'Organize the copy into useful sections', 'No H2 headings extracted.', 'Subheadings help people scan and understand the page.', 'Group existing content by customer need and label each section clearly.');
  const missing = page.images.filter(i => i.alt === null && !i.decorative);
  if (missing.length) add('image-alt', 'Medium Impact', 'Images', 'Review images without alt attributes', `${missing.length} of ${page.images.length} images have no alt attribute.`, 'Meaningful images need accessible text alternatives. Decorative images should use empty alt text.', 'Describe informative images accurately; use alt="" for decorative images. Do not insert keywords unrelated to the image.');
  if (page.images.some(i => i.alt !== null && /^(image|photo|picture|img\d*|\w+\.(jpg|png|webp))$/i.test(i.alt))) add('weak-alt', 'Low Impact', 'Image alt text', 'Replace generic image descriptions', page.images.filter(i => /^(image|photo|picture|img\d*|\w+\.(jpg|png|webp))$/i.test(i.alt || '')).map(i => i.alt).join('; '), 'Generic filenames and labels rarely convey an informative image’s meaning.', 'Review each image visually and write a concise description where the image carries information.');
  if (!page.internalLinks.length || !keywords.some(k => k.supportingAnchors.length)) add('internal-links', 'Medium Impact', 'Internal links', 'Strengthen relevant internal navigation', `${page.internalLinks.length} internal links; ${primary.supportingAnchors.length} topic-related anchors for the primary keyword.`, 'Useful related links support visitors exploring a subject. This audit does not measure incoming internal links.', 'Link to real related services or useful supporting pages using descriptive anchors. Also review links into this page in a future site-wide audit.');
  if (page.internalLinks.length > 200) add('many-links', 'Low Impact', 'Internal links', 'Review navigation density', `${page.internalLinks.length} internal link elements detected, including repeated navigation.`, 'Large menus can overwhelm people; link count alone does not establish an SEO problem.', 'Check whether repeated or low-value navigation distracts from the next useful step. Keep links that serve visitors.');
  if (keywords.some(k => k.possibleStuffing)) add('stuffing', 'High Impact', 'Body copy', 'Review unusually repetitive exact phrases', keywords.filter(k => k.possibleStuffing).map(k => `${k.keyword}: ${k.phraseOccurrences} detected occurrences`).join('; '), 'Heavy exact-phrase repetition can make copy unnatural. This is a review flag, not a target density.', 'Read the page aloud and remove repetitive phrases that add no meaning. Use accurate topic vocabulary naturally.');
  if (!page.https) add('https', 'High Impact', 'Transport', 'Serve the page over HTTPS', page.url, 'HTTPS protects the connection and improves user trust.', 'Install a valid TLS certificate and redirect the HTTP URL to its HTTPS equivalent.');
  if (!page.viewport) add('viewport', 'Medium Impact', 'Viewport', 'Declare a mobile viewport', 'No viewport meta tag extracted.', 'Without a viewport declaration, mobile browsers may display a desktop-width layout.', 'Add a responsive viewport and test the actual page on mobile.', '<meta name="viewport" content="width=device-width, initial-scale=1">');
  if (!page.canonical || page.canonicals.length > 1) add('canonical', 'Medium Impact', 'Canonical', 'Review the canonical declaration', page.canonicals.join('; ') || 'No canonical tag extracted.', 'A consistent canonical helps communicate the preferred URL when duplicate URLs exist.', 'Declare one appropriate canonical URL. A missing tag alone does not prove duplicate-content problems.', page.url);
  else if (page.canonical.replace(/\/$/, '') !== page.url.replace(/\/$/, '')) add('canonical-other', 'High Impact', 'Canonical', 'Confirm the canonical points to the intended page', page.canonical, 'This page nominates a different preferred URL; it may be intentional.', 'Confirm whether the canonical destination should receive consolidation signals. Use a self-reference only if this is the preferred page.');
  if (page.schemaErrors.length) add('schema-invalid', 'Medium Impact', 'JSON-LD', 'Repair malformed structured data', page.schemaErrors.join('; '), 'Invalid JSON prevents reliable interpretation of the affected block.', 'Validate the original JSON-LD and repair syntax. Only mark up facts visible and supported on the page.');
  if (primary.intent.score < 50) add('intent', 'High Impact', 'Page type', 'Review page format against likely search intent', `${primary.intent.pageType}; inferred intent: ${primary.intent.labels.join(', ')}.`, primary.intent.explanation, 'Review live search results manually and decide whether a service landing page or explanatory article better serves this query.');
  if (keywords.some(k => k.intent.local)) {
    if (keywords.some(k => k.intent.local && k.localScore < 40)) add('local-relevance', 'High Impact', 'Local content', 'Make the genuine service area explicit', `Matched places: ${keywords.flatMap(k => k.localMatches).join(', ') || 'none detected'}.`, 'A local visitor needs to know whether the business serves their area.', 'State the actual areas served in prominent copy. Add accurate local examples and FAQs only for real operations.');
    if (!page.signals.localSchema) add('local-schema', 'Medium Impact', 'Structured data', 'Consider appropriate local business markup', `Detected schema types: ${page.schemaTypes.join(', ') || 'none'}.`, 'Appropriate structured data can clarify business details; it does not guarantee a rich result.', 'If eligible, add the most specific supported business type with verified name, contact and service-area information.');
    if (!page.signals.contact) add('contact', 'High Impact', 'Contact', 'Make contact information easy to find', 'No telephone link, email link, or contact anchor detected.', 'Local customers need an obvious way to confirm availability or request service.', 'Add a visible contact route using the business’s verified details.');
  }
  if (primary.intent.labels.some(l => ['Transactional', 'Commercial investigation'].includes(l))) {
    if (!page.signals.cta) add('cta', 'High Impact', 'Conversion', 'Provide a clear next step', 'No recognized CTA link or submit control detected.', 'Visitors with buying intent need a relevant route to act.', 'Add a useful quote, booking, purchase, or contact action suited to the real business.');
    if (!page.signals.trust && !page.signals.reviews) add('trust', 'Medium Impact', 'Trust content', 'Support claims with verifiable proof', 'No recognized trust or review wording detected.', 'Relevant evidence helps prospective customers make a decision.', 'Where available, add genuine project examples, qualifications, or permissioned customer reviews. Never invent testimonials or credentials.');
  }
  return issues.sort((a, b) => priorityOrder.indexOf(a.priority) - priorityOrder.indexOf(b.priority));
}

export function makeImprovements(page, keywords, issues, gaps) {
  const topic = keywords[0].keyword;
  const supportedTopic = keywords[0].body.coverage >= .5;
  let title = keywords[0].title.coverage >= .8 ? page.title : page.h1[0] || page.title || '';
  if (!title && supportedTopic) title = topic;
  if (title && !page.title && page.businessName && !title.toLowerCase().includes(page.businessName.toLowerCase()) && title.length + page.businessName.length < 72) title += ` | ${page.businessName}`;
  const sentences = page.body.split(/(?<=[.!?])\s+/).filter(s => s.length >= 40 && s.length <= 230);
  const topicalSentence = [...sentences].sort((a,b) => matchKeyword(b,topic).coverage - matchKeyword(a,topic).coverage)[0] || '';
  const description = page.description && matchKeyword(page.description,topic).coverage >= .5 && page.description.length <= 180 ? page.description : topicalSentence || page.description;
  const drafts = [
    { element: 'SEO title', current: page.title, suggested: title || 'Insufficient retrieved evidence to suggest a title.', note: 'Preserves existing title/heading wording. Confirm query alignment and improve the differentiator using verified business details.' },
    { element: 'Meta description', current: page.description, suggested: description || 'Insufficient retrieved evidence to draft a description.', note: 'Retains a relevant existing description or selects a topical sentence from retrieved copy. Refine the benefit and next step using verified business details.' },
    { element: 'H1', current: page.h1.join(' | '), suggested: page.h1.length === 1 && keywords[0].h1.coverage >= .8 ? page.h1[0] : supportedTopic ? topic : page.h1[0] || title || 'Confirm the page subject before writing an H1.', note: supportedTopic ? 'Preserve the current H1 when it describes the page clearly. Otherwise verify this topic-led draft.' : 'The query has little support in the retrieved copy. Confirm page/query alignment before changing the subject.' }
  ];
  const outline = [{ level: 'H1', text: drafts[2].suggested, reason: 'Clear page purpose; verify the actual offering.' }, { level: 'Intro', text: `Introduce ${topic}`, reason: 'Explain what the visitor will find using verified facts.' }];
  const seen = new Set();
  for (const h of page.h2.slice(0, 6)) { outline.push({ level: 'H2', text: h, reason: 'Retained from the target page; review order and usefulness.' }); seen.add(h.toLowerCase()); }
  for (const g of gaps.slice(0, 4)) if (!seen.has(g.topic.toLowerCase())) { outline.push({ level: 'H2', text: g.topic, reason: g.usefulness }); seen.add(g.topic.toLowerCase()); }
  if (issues.some(i => i.id === 'trust')) outline.push({ level: 'H2', text: 'Relevant project examples or verified qualifications', reason: 'Include only if the business can provide authentic evidence.' });
  if (!page.signals.faq) outline.push({ level: 'H2', text: 'Questions customers ask before choosing', reason: 'Answer useful questions; omit if the page already answers them naturally.' });
  if (keywords[0].intent.labels.includes('Transactional')) outline.push({ level: 'CTA', text: 'A clear next step', reason: 'Use the actual contact or booking path.' });
  const faq = gaps.filter(g => g.group === 'Missing Questions').map(g => g.topic);
  return { drafts, outline, faq, internalLinkOpportunities: page.internalLinks.filter(l => !l.anchor || /^(read more|learn more|click here)$/i.test(l.anchor)).slice(0, 8).map(l => ({ ...l, suggestion: 'Describe the destination’s actual subject in the anchor. Review destination content before choosing wording.' })) };
}
