import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import * as cheerio from 'cheerio';
import { crawlPage } from '../server/crawler.js';
import { parsePage } from '../server/parser.js';
const origin = process.env.TEST_ORIGIN || 'http://127.0.0.1:3000';
const target = process.env.TEST_TARGET || 'https://example.com/';
const keyword = process.env.TEST_KEYWORD || 'example domain';
const snapshot = await crawlPage(target);
const page = parsePage(snapshot);
const $ = cheerio.load(snapshot.html);
assert.equal(page.title, $('title').first().text().trim());
assert.equal(page.description, ($('meta[name="description"]').attr('content') || '').trim());
assert.deepEqual(page.h1, $('h1').map((_,e)=>$(e).text().replace(/\s+/g,' ').trim()).get());
assert.deepEqual(page.h2, $('h2').map((_,e)=>$(e).text().replace(/\s+/g,' ').trim()).get());
const content = $('main,[role="main"]').first().length ? $('main,[role="main"]').first() : $('article').first().length ? $('article').first() : $('body');
const text = content.find('p').filter((_,el)=>!$(el).closest('nav,header,footer,aside,[hidden],[aria-hidden="true"]').length).first().text().replace(/\s+/g,' ').trim();
assert.ok(page.body.includes(text), 'First paragraph must match the retrieved page');
const response = await fetch(`${origin}/api/analyze`, { method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({targetUrl:target,keywords:keyword,competitorUrls:['https://www.iana.org/help/example-domains','https://does-not-exist.invalid/']}) });
assert.equal(response.status,200);
const events = (await response.text()).trim().split('\n').map(JSON.parse);
const report = events.find(e=>e.type==='report')?.report;
assert.ok(report,JSON.stringify(events)); assert.equal(report.target.page.title,page.title); assert.equal(report.target.page.description,page.description); assert.deepEqual(report.target.page.h1,page.h1);
assert.equal(report.competitors.length,2); assert.ok(report.competitors[1].error); assert.ok(report.target.score.overall >= 0 && report.target.score.overall <= 100);
assert.ok(events.filter(e=>e.type==='progress').length>=6);
await mkdir('artifacts',{recursive:true}); await writeFile('artifacts/live-report.json',JSON.stringify(report,null,2)); await writeFile('artifacts/live-source.html',snapshot.html);
console.log(JSON.stringify({ok:true,target,title:page.title,description:page.description,h1:page.h1,h2:page.h2,firstParagraph:text,score:report.target.score.overall,competitors:report.competitors.map(c=>({url:c.url,title:c.analysis?.page.title,error:c.error})),aiStatus:report.ai.status},null,2));
